use std::hash::Hash;
use revm_primitives::{AccountInfo, U256};
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    METHOD_ELF, METHOD_ID
};
use risc0_zkvm::{default_prover, ExecutorEnv};

use simple_hasher::SimpleSha256Hasher;


fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // For example:
    let input: u64 = 15 * u64::pow(2, 27) + 1;

    let mut account_info = AccountInfo::from_balance(U256::from(100_000));
    account_info.nonce = input;

    let mut hasher = SimpleSha256Hasher::new();
    account_info.hash(&mut hasher);
    let result = hasher.result();

    tracing::info!("Account info: {:?}, hash: {:?}", account_info, result);

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // An default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .write(&account_info)
        .unwrap()
        .write(&result)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    let receipt = prover
        .prove(env, METHOD_ELF)
        .unwrap();

    // TODO: Implement code for retrieving receipt journal here.

    // For example:
    let _output: u32 = receipt.journal.decode().unwrap();

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt
        .verify(METHOD_ID)
        .unwrap();
}
